/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110062-g9413bdc381-20230322"
#endif /* AVUTIL_FFVERSION_H */
